i = 0;

% i = i+1;
% db(i).mouse_name    = 'SS041';
% db(i).date          = '2015-08-10';
% db(i).expts         = 1; % which experiments to cluster together
% db(i).planesToProcess = 2:3;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b2';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 1]; % splits frame into 4 parts along y direction
% % db(i).RootDir       = fullfile(db(i).mouse_name, db(i).date, '2P');

% i = i+1;
% db(i).mouse_name    = 'M150305_SS041';
% db(i).date          = '2015-08-11';
% db(i).expts         = 1; % which experiments to cluster together
% db(i).planesToProcess = 2:4;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b2';
% db(i).diameter      = 10;
% db(i).numBlocks     = [6 3]; % splits frame into 4 parts along y direction
% db(i).stopSourcery  = 1/10;
% % db(i).RootDir       = fullfile(db(i).mouse_name, db(i).date, '2P');
% 
% i = i+1;
% db(i).mouse_name    = {'SS041', 'M150305_SS041'};
% db(i).date          = {'2015-08-12', '2015-08-12'};
% db(i).expts         = {1, 1}; % which experiments to cluster together
% db(i).planesToProcess = 2:4;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b2';
% db(i).diameter      = 10;
% db(i).numBlocks     = [9 7]; % splits frame into 4 parts along y direction
% db(i).stopSourcery  = 1/10;
% % db(i).RootDir       = fullfile(db(i).mouse_name, db(i).date, '2P');
% 
% i = i+1;
% db(i).mouse_name    = 'SS041';
% db(i).date          = '2015-08-13';
% db(i).expts         = 2; % which experiments to cluster together
% db(i).planesToProcess = 2:3;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b2';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction
% db(i).stopSourcery  = 1/10;
% % db(i).RootDir       = fullfile(db(i).mouse_name, db(i).date, '2P');

% i = i+1;
% db(i).mouse_name    = 'SS047';
% db(i).date          = '2015-11-10';
% db(i).expts         = 4:6; % which experiments to cluster together
% db(i).planesToProcess = 2:4;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction
% 
i = i+1;
db(i).mouse_name    = 'SS041';
db(i).date          = '2015-08-12';
db(i).expts         = 1; % which experiments to cluster together
db(i).planesToProcess = 2:4;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b2';
db(i).diameter      = 10;
db(i).numBlocks     = [9 7]; % splits frame into 4 parts along y direction
db(i).stopSourcery  = 1/10;

i = i+1;
db(i).mouse_name    = {'SS047', 'M150610_SS047'};
db(i).date          = {'2015-11-11', '2015-11-11'};
db(i).expts         = {[1 2], 2}; % which experiments to cluster together
db(i).planesToProcess = 2:5;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction

i = i+1;
db(i).mouse_name    = 'SS047';
db(i).date          = '2015-11-12';
db(i).expts         = 1; % which experiments to cluster together
db(i).planesToProcess = 2:4;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction

i = i+1;
db(i).mouse_name    = 'SS047';
db(i).date          = '2015-11-17';
db(i).expts         = 1; % which experiments to cluster together
db(i).planesToProcess = 2:4;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction

i = i+1;
db(i).mouse_name    = 'SS047';
db(i).date          = '2015-11-17';
db(i).expts         = 2; % which experiments to cluster together
db(i).planesToProcess = 2:4;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction

i = i+1;
db(i).mouse_name    = {'SS047', 'M150610_SS047'};
db(i).date          = {'2015-11-18', '2015-11-18'};
db(i).expts         = {1:2, 1}; % which experiments to cluster together
db(i).planesToProcess = 2:4;
db(i).AlignToRedChannel = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [6 3]; % splits frame into parts along y and x direction

% i = i+1;
% db(i).mouse_name    = 'SS047';
% db(i).date          = '2015-11-24';
% db(i).expts         = 3; % which experiments to cluster together
% db(i).planesToProcess = 2:4;
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction
% db(i).RootDir       = fullfile(db(i).mouse_name, db(i).date, '2P');


% i = i+1;
% db(i).mouse_name    = 'M160706_SS066';
% db(i).date          = '2016-09-01';
% db(i).expts         = 2; % which experiments to cluster together
% db(i).AlignToRedChannel = 0;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 60;
% 
% i = i+1;
% db(i).mouse_name    = 'M160706_SS066';
% db(i).date          = '2016-09-06';
% db(i).expts         = 2:4; % which experiments to cluster together
% db(i).AlignToRedChannel = 0;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 60;
% 
% i = i+1;
% db(i).mouse_name    = 'M160706_SS066';
% db(i).date          = '2016-09-08';
% db(i).expts         = 2:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 0;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 60;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS069';
% db(i).date          = '2016-10-11';
% db(i).expts         = 3:4; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 4;
% db(i).maxregshift = 60;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS069';
% db(i).date          = '2016-10-13';
% db(i).expts         = [1:4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).splitBlocks   = 'none'; %{[171 170 171],[512]};
% db(i).splitROIs     = 0;
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 60;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS069';
% db(i).date          = '2016-10-20';
% db(i).expts         = 3:5; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 4:8;
% db(i).diameter = 4;
% db(i).maxregshift = 80;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS069';
% db(i).date          = '2016-10-21';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).numBlocks     = [5 1];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 4:8;
% db(i).diameter = 4;
% db(i).maxregshift = 80;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS070';
% db(i).date          = '2016-10-12';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).numBlocks     = [3 1];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 50;
% 
% i = i+1;
% db(i).mouse_name    = 'M160923_SS070';
% db(i).date          = '2016-10-18';
% db(i).expts         = 1:4; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).numBlocks     = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 50;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS070';
% db(i).date          = '2016-10-20';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).numBlocks     = [5 1];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 4:8;
% db(i).diameter = 5;
% db(i).maxregshift = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'M160923_SS070';
% db(i).date          = '2016-10-21';
% db(i).expts         = 2; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).numBlocks     = [5 1];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 4:8;
% db(i).diameter = 5;
% db(i).maxregshift = 80;

% i = i+1;
% db(i).mouse_name    = 'M160923_SS071';
% db(i).date          = '2016-10-18';
% db(i).expts         = 2:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).smooth_time_space  = [];
% db(i).alignTargetImages = true;
% db(i).targetImage = 1;
% db(i).alignAcrossPlanes = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate = 6:16;
% db(i).diameter = 5;
% db(i).maxregshift = 40;