i = 0;

i = i+1;
db(i).mouse_name    = 'M150410_SS044';
db(i).date          = '2015-05-15';
db(i).expts         = [2:5 7]; % which experiments to cluster together
db(i).AlignToRedChannel = 1;
db(i).REDbinary     = 0;
db(i).redMeanImg    = 1;
db(i).microID       = 'b';
db(i).diameter      = 10;
db(i).numBlocks     = [5 1];
db(i).targetImage   = 1;
db(i).alignAcrossPlanes       = 1;
db(i).alignTargetImages       = 1;
db(i).interpolateAcrossPlanes = 1;
db(i).planesToInterpolate     = 2:4;
% db(i).maxregshift   = 80;

% i = i+1;
% db(i).mouse_name    = 'M170821_SS075';
% db(i).date          = '2017-09-13';
% db(i).expts         = [1 2 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;

% i = i+1;
% db(i).mouse_name    = 'SS075';
% db(i).date          = '2017-09-27';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'M170821_SS076';
% db(i).date          = '2017-09-12';
% db(i).expts         = 4:5; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'M170821_SS076';
% db(i).date          = '2017-09-27';
% db(i).expts         = 1:2; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS076';
% db(i).date          = '2017-10-02';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'M170821_SS076';
% db(i).date          = '2017-10-02';
% db(i).expts         = 5; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS076';
% db(i).date          = '2017-10-03';
% db(i).expts         = [1 3:5]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS076';
% db(i).date          = '2017-10-04';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'M170821_SS077';
% db(i).date          = '2017-09-13';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS077';
% db(i).date          = '2017-09-28';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS077';
% db(i).date          = '2017-10-03';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS077';
% db(i).date          = '2017-10-05';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% % 
% i = i+1;
% db(i).mouse_name    = 'M170821_SS078';
% db(i).date          = '2017-09-11';
% db(i).expts         = [2 8]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS078';
% db(i).date          = '2017-09-28';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS078';
% db(i).date          = '2017-09-29';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS078';
% db(i).date          = '2017-10-02';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS078';
% db(i).date          = '2017-10-04';
% db(i).expts         = [1 3 4]; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;
% 
% i = i+1;
% db(i).mouse_name    = 'SS078';
% db(i).date          = '2017-10-05';
% db(i).expts         = 1:3; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).REDbinary     = 0;
% db(i).redMeanImg    = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 4;
% db(i).numBlocks     = [5 1];
% db(i).targetImage   = 1;
% db(i).alignAcrossPlanes       = 1;
% db(i).alignTargetImages       = 1;
% db(i).interpolateAcrossPlanes = 1;
% db(i).planesToInterpolate     = 4:8;
% db(i).maxregshift   = 80;

% ------------------------------------------------------------------------
% i = i+1;
% db(i).mouse_name    = 'M150610_SS047';
% db(i).date          = '2015-11-23';
% db(i).expts         = 1; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction
% db(i).deconvType    = 'OASIS';
% db(i).sensorTau     = 0.7;
% db(i).newops        = 1;
% db(i).runningBaseline = 60;

% i = i+1;
% db(i).mouse_name    = {'SS048', 'M150611_SS048'};
% db(i).date          = {'2015-09-03', '2015-09-03'};
% db(i).expts         = {1, 1}; % which experiments to cluster together
% db(i).AlignToRedChannel = 1;
% db(i).microID       = 'b2';
% db(i).diameter      = 10;
% db(i).numBlocks     = [8 3]; % splits frame into 4 parts along y direction